import sys
import os
import textwrap

def forge_component(name):
    base_dir = "src/components"
    os.makedirs(base_dir, exist_ok=True)
    
    component_file = f"{base_dir}/{name}.tsx"
    test_file = f"{base_dir}/{name}.test.tsx"
    
    # Check if exists
    if os.path.exists(component_file):
        print(f"Error: {component_file} already exists.")
        return

    # Component Template
    component_code = textwrap.dedent(f"""\
        'use client';
        
        import React from 'react';
        
        interface {name}Props {{
            title?: string;
        }}
        
        export const {name}: React.FC<{name}Props> = ({{ title = "{name}" }}) => {{
            return (
                <div className="p-4 bg-white rounded-lg shadow-md border border-gray-200 hover:border-blue-500 transition-colors">
                    <h2 className="text-xl font-bold text-gray-800">{{title}}</h2>
                    <p className="text-gray-600 mt-2">Generated by Antigravity Forge.</p>
                </div>
            );
        }};
    """)

    # Test Template
    test_code = textwrap.dedent(f"""\
        import {{ render, screen }} from '@testing-library/react';
        import {{ {name} }} from './{name}';
        import {{ describe, it, expect }} from 'vitest';

        describe('{name}', () => {{
            it('renders successfully', () => {{
                render(<{name} />);
                expect(screen.getByText('{name}')).toBeDefined();
            }});
            
            it('renders custom title', () => {{
                render(<{name} title="Custom Title" />);
                expect(screen.getByText('Custom Title')).toBeDefined();
            }});
        }});
    """)
    
    with open(component_file, "w") as f:
        f.write(component_code)
    
    with open(test_file, "w") as f:
        f.write(test_code)
        
    print(f"Forged {name} successfully at {component_file} and {test_file}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python forge.py <ComponentName>")
    else:
        forge_component(sys.argv[1])
